name: Angular CD Blue-Green

on:
  workflow_call:
    inputs:
      branch-name:
        description: 'Branch que disparou o deploy'
        required: true
        type: string
      build-path:
        description: 'Caminho do build a ser deployado'
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      S3_BUCKET_NAME:
        required: true
      CLOUDFRONT_ID:
        required: true
      AWS_REGION:
        required: false
      PAT_TOKEN:
        required: true   # Token para abrir PR

jobs:
  cd-bluegreen:
    uses: ./.github/workflows/cd-workflows/deploy-s3.yml
    with:
      build-path: ${{ inputs.build-path }}
      inactive-folder: blue   # aqui podemos usar um passo detect anterior para alternar blue/green

  swap-cloudfront:
    needs: cd-bluegreen
    uses: ./.github/workflows/cd-workflows/swap-cloudfront.yml
    with:
      deploy-path: ${{ needs.cd-bluegreen.outputs.DEPLOY_PATH }}

  cleanup:
    needs: swap-cloudfront
    uses: ./.github/workflows/cd-workflows/cleanup-old-builds.yml

  open-pr-main:
    needs: cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Open Pull Request to main
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          source_branch: ${{ inputs.branch-name }}
          destination_branch: main
          pr_title: "Merge ${{ inputs.branch-name }} into main"
          pr_body: |
            PR automática criada pelo pipeline.
            Branch de origem: `${{ inputs.branch-name }}`
