name: Angular CD Blue-Green

on:
  workflow_call:
    inputs:
      branch-name:
        description: 'Branch que disparou o deploy'
        required: true
        type: string
      build-path:
        description: 'Caminho do build a ser deployado'
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID: { required: true }
      AWS_SECRET_ACCESS_KEY: { required: true }
      S3_BUCKET_NAME: { required: true }
      CLOUDFRONT_ID: { required: true }
      AWS_REGION: { required: false }
      PAT_TOKEN: { required: true }

jobs:
  deploy-s3:
    uses: ./.github/workflows/deploy-s3.yml
    with:
      build-path: ${{ inputs.build-path }}
      inactive-folder: blue
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  swap-cloudfront:
    needs: deploy-s3
    uses: ./.github/workflows/swap-cloudfront.yml
    with:
      deploy-path: ${{ needs.deploy-s3.outputs.DEPLOY_PATH }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CLOUDFRONT_ID: ${{ secrets.CLOUDFRONT_ID }}

  cleanup:
    needs: swap-cloudfront
    uses: ./.github/workflows/cleanup-old-builds.yml
    with:
      deploy-path: ${{ needs.deploy-s3.outputs.DEPLOY_PATH }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

  open-pr-main:
    needs: cleanup
    uses: ./.github/workflows/open-pr-main.yml
    with:
      branch-name: ${{ inputs.branch-name }}
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
