name: Angular CI

on:
  workflow_call:
    inputs:
      branch-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-folder: ${{ steps.set-output.outputs.build-folder }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run build -- --configuration production

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          path: dist/vyracare-app-shell

      - name: Set build folder output
        id: set-output
        run: echo "build-folder=dist/vyracare-app-shell" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-dist
          path: dist/vyracare-app-shell

      - name: Run unit tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

  open-pr-develop:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/feat/') || startsWith(github.ref, 'refs/heads/fix/') || startsWith(github.ref, 'refs/heads/feature/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Open Pull Request to develop
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.PAT_TOKEN }}  # PAT com escopo 'repo'
          source_branch: ${{ github.ref_name }}
          destination_branch: develop
          pr_title: "PR automatic ${{ github.ref_name }} into develop"
          pr_body: |
            PR automática criada pelo pipeline.
            Branch de origem: `${{ github.ref_name }}`
          pr_draft: false
          allow_empty: false

      - name: Check PR creation result
        run: |
          if [ -z "${{ steps.open-pr.outputs.pull_request_url }}" ]; then
            echo "⚠️ PR não criado! Verifique se o PAT tem permissão e se a branch de destino está protegida."
            exit 1
          else
            echo "✅ PR criado com sucesso: ${{ steps.open-pr.outputs.pull_request_url }}"
          fi
