name: Angular CI Pipeline

on:
  push:
    branches:
      - 'feat/*'
      - 'fix/*'
      - 'feature/*'
      - 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.set-output.outputs.artifact-name }}

    steps:
      # 1️⃣ Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build Angular
      - name: Build Angular
        run: npm run build -- --configuration production

      # 5️⃣ Run Unit Tests
      - name: Run unit tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      # 6️⃣ Upload Artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          path: dist/vyracare-app-shell

      # 7️⃣ Output name
      - name: Set artifact output
        id: set-output
        run: echo "artifact-name=angular-dist" >> $GITHUB_OUTPUT
