name: DEPLOY

on:
  push:
    branches:
      - "main"
      - "develop"

jobs:
  call-cd-workflow:
    uses: ./.github/workflows/cd-bluegreen.yml
    with:
      s3-bucket: ${{ secrets.S3_BUCKET_NAME }}
      cloudfront-id: ${{ secrets.CLOUDFRONT_ID }}
      aws-region: us-east-1
      build-path: dist/vyracare-app-shell
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
