name: DEPLOY

on:
  push:
    branches:
      - develop

jobs:
  cd-angular:
    uses: ./.github/workflows/cd-angular.yml
    with:
      branch-name: ${{ github.ref_name }}
      build-path: dist/vyracare-app-shell
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      CLOUDFRONT_ID: ${{ secrets.CLOUDFRONT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
