name: Deploy VyraCare Shell

# Executa quando houver push na branch main
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Faz checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Instalar dependências
      - name: Install dependencies
        run: npm ci

      # Build do Angular em produção
      - name: Build Angular Shell
        run: npm run build -- --configuration production

      # Configurar AWS CLI (usar secrets do GitHub)
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # substitua se for outra região

      # Sincronizar build com S3
      - name: Deploy to S3
        run: |
          aws s3 sync ./dist/shell s3://vyracare-app-shell --delete

      # Invalidar cache do CloudFront
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_ID \
            --paths "/*"

    env:
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      CLOUDFRONT_ID: ${{ secrets.CLOUDFRONT_ID }}
