name: Open PR to main

on:
  workflow_call:
    inputs:
      branch-name:
        description: 'Branch que disparou o deploy'
        required: true
        type: string
    secrets:
      PAT_TOKEN:
        required: true

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Open Pull Request to main
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          source_branch: ${{ inputs.branch-name }}
          destination_branch: main
          pr_title: "Merge ${{ inputs.branch-name }} into main"
          pr_body: "PR automática criada pelo pipeline. Branch de origem: `${{ inputs.branch-name }}`"
