name: PUBLISH

on:
  push:
    branches:
      - develop  # Dispara quando houver merge na develop

jobs:
  publish:
    uses: vyracare/vyracare-infra-pipes-angular/.github/workflows/cd-angular.yml@main
    with:
      branch-name: ${{ github.ref_name }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      CLOUDFRONT_ID: ${{ secrets.CLOUDFRONT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
