name: Interactive Rollback

on:
  workflow_dispatch

jobs:
  rollback:
    runs-on: ubuntu-latest
    env:
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      CLOUDFRONT_ID: ${{ secrets.CLOUDFRONT_ID }}
      AWS_REGION: us-east-1
    steps:
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download deploy history
        run: |
          aws s3 cp s3://$S3_BUCKET_NAME/deploy-history.json ./deploy-history.json

      - name: Show deploy history
        id: list
        run: |
          echo "Available deploys:"
          jq -r '.[] | "\(.timestamp) -> \(.path) | active: \(.active)"' deploy-history.json
          # Save all paths to output
          DEPLOY_PATHS=$(jq -r '.[].path' deploy-history.json | paste -sd "," -)
          echo "paths=$DEPLOY_PATHS" >> $GITHUB_OUTPUT

      - name: Prompt for rollback path
        id: prompt
        run: |
          echo "You can choose one of the following paths for rollback:"
          echo "${{ steps.list.outputs.paths }}"
          # For simplicity, read input from GitHub Actions input
          echo "rollback-path=$(gh workflow view --json inputs --jq '.inputs.rollback-to.value')" >> $GITHUB_OUTPUT

      - name: Rollback CloudFront
        run: |
          PATH_TO_ROLLBACK="${{ github.event.inputs.rollback-to }}"
          echo "Rolling back to $PATH_TO_ROLLBACK"
          DISTRIBUTION_CONFIG=$(aws cloudfront get-distribution-config --id $CLOUDFRONT_ID)
          ETAG=$(echo $DISTRIBUTION_CONFIG | jq -r '.ETag')
          CONFIG=$(echo $DISTRIBUTION_CONFIG | jq '.DistributionConfig')
          UPDATED_CONFIG=$(echo $CONFIG | jq --arg path "$PATH_TO_ROLLBACK" '.Origins.Items[0].OriginPath=$path')
          aws cloudfront update-distribution --id $CLOUDFRONT_ID --if-match $ETAG --distribution-config "$UPDATED_CONFIG"
