name: ROLLBACK MANUAL

on:
  workflow_dispatch:
    inputs:
      rollback-path:
        description: 'Versão do rollback (ex: /blue/20250914120000)'
        required: false

jobs:
  rollback:
    uses: vyracare/vyracare-infra-pipes-angular/.github/workflows/rollback-generic.yml@main
    with:
      rollback-path: ${{ github.event.inputs.rollback-path }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      CLOUDFRONT_ID: ${{ secrets.CLOUDFRONT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
