name: Rollback

on:
  workflow_dispatch:
    inputs:
      rollback-path:
        description: 'Versão do rollback (ex: /blue/20250914120000)'
        required: false

jobs:
  call-rollback:
    uses: ./.github/workflows/rollback-bluegreen.yml
    with:
      rollback-path: ${{ github.event.inputs.rollback-path }}
      s3-bucket: ${{ secrets.S3_BUCKET_NAME }}
      cloudfront-id: ${{ secrets.CLOUDFRONT_ID }}
      aws-region: us-east-1
