name: Reusable Blue-Green Rollback

on:
  workflow_dispatch:
    inputs:
      rollback-path:
        description: 'Caminho da versão para rollback (ex: /blue/20250914120000). Se vazio, reverterá para a última versão ativa.'
        required: false
        default: ''
      s3-bucket:
        description: 'Nome do bucket S3'
        required: true
      cloudfront-id:
        description: 'ID da distribuição CloudFront'
        required: true
      aws-region:
        description: 'Região AWS'
        required: true
        default: 'us-east-1'

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.aws-region }}

      - name: Detect rollback path
        id: detect
        run: |
          if [ -z "${{ github.event.inputs.rollback-path }}" ]; then
            ACTIVE=$(aws cloudfront get-distribution --id ${{ github.event.inputs.cloudfront-id }} | jq -r '.Distribution.Origins.Items[0].OriginPath')
            echo "ROLLBACK_PATH=$ACTIVE" >> $GITHUB_ENV
          else
            echo "ROLLBACK_PATH=${{ github.event.inputs.rollback-path }}" >> $GITHUB_ENV
          fi
          echo "Rollback target: $ROLLBACK_PATH"

      - name: Rollback CloudFront
        run: |
          DISTRIBUTION_CONFIG=$(aws cloudfront get-distribution-config --id ${{ github.event.inputs.cloudfront-id }})
          ETAG=$(echo $DISTRIBUTION_CONFIG | jq -r '.ETag')
          CONFIG=$(echo $DISTRIBUTION_CONFIG | jq '.DistributionConfig')
          UPDATED_CONFIG=$(echo $CONFIG | jq --arg path "$ROLLBACK_PATH" '.Origins.Items[0].OriginPath=$path')
          aws cloudfront update-distribution --id ${{ github.event.inputs.cloudfront-id }} --if-match $ETAG --distribution-config "$UPDATED_CONFIG"
          echo "Rollback realizado para $ROLLBACK_PATH"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ github.event.inputs.cloudfront-id }} --paths "/*"
          echo "Cache do CloudFront invalidado"
